# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QCompleter, QTableWidgetItem
import numpy as np
from dataComps.Constants import Constants, OrderType
from .RSITrackerWindow import RSITrackerWindow
import sys, threading
import pandas as pd

from uiComps.Logging import Logger
import webbrowser

from dataComps.UserDataManagement import readStockList
from dataComps.ibFTPdata import getShortDataFor
from dataComps.HistoricalDataManagement import HistoricalDataManager

class RSITracker(RSITrackerWindow):

    time_period = "Month"

    def __init__(self, history_manager):
        super().__init__()

        self.data_management = history_manager
        self.data_management.data_updater.connect(self.dataUpdate)
        
        file_name, _ = self.stock_lists[0]
        self.stock_list = readStockList(file_name)


    def listSelection(self, value):
        self.bull_table.clearContents()
        self.bull_table.setRowCount(0)
        self.bear_table.clearContents()
        self.bear_table.setRowCount(0)
        
        file_name, _ = self.stock_lists[value]
        self.stock_list = readStockList(file_name)

    def priceUpdate(self):
        self.data_management.fetchPricesFor(self.stock_list)

    def dataUpdate(self, signal):
        print(f"RSITracker.dataUpdate: {signal}")

        if signal == Constants.HISTORICAL_DATA_FETCH_COMPLETE:
            histDF = self.data_management.historicalDF
            stock_ids = histDF.UID.unique().tolist()
            bar_types = ['5 mins', '15 mins', '1 hour', '4 hours', '8 hours', '1 day', '1 week'] #, '1 month']

            rsi_values = np.zeros((len(stock_ids), len(bar_types)))
            
        
            period = 14
            for uid_index, uid in enumerate(stock_ids):
                stock_frame = histDF.loc[histDF.UID == uid]
                for bar_index, bar_type in enumerate(bar_types):
                    
                    closes = stock_frame[stock_frame.BarType == bar_type].Close.to_numpy()
                    
                    diffs = closes[1:] - closes[:-1] 

                    ups = diffs.copy()
                    downs = diffs.copy()
                    ups[ups < 0] = 0
                    downs[downs > 0] = 0
                    downs = np.absolute(downs)

                    up_ema = pd.Series.ewm(pd.Series(ups), alpha=1/period).mean().values[-1]
                    down_ema = pd.Series.ewm(pd.Series(downs), alpha=1/period).mean().values[-1]
                    # up_ema = self.get_ema(ups)
                    # down_ema = self.get_ema(downs)

                    rsi = 100 - 100/(1+up_ema/down_ema)

                    rsi_values[uid_index, bar_index] = rsi

            self.setData(stock_ids, rsi_values)
            self.fetch_button.setEnabled(True)


    def get_ema(self, prices, days=14, counter=0):
        if len(prices) > days:
            counter += 1
            alpha = 1/days
            return prices[-1] * alpha + (1 - alpha) * self.get_ema(prices[:-1], days, counter)
        else:
            return prices.mean()


    def fetchStocks(self):
        self.fetch_button.setEnabled(False)

        self.data_management.getBars(self.stock_list)


    def fetchShortRates(self):
        self.fee_rates = np.ones((len(self.stock_list))) * 500
        self.short_availability = [""] * len(self.stock_list)
        for index, stock in enumerate(self.stock_list):
            short_data = getShortDataFor(stock)
            print(f"For {stock} we found {short_data}")
            if len(short_data) != 0:
                self.fee_rates[index] = float(short_data[6])
                self.short_availability[index] = short_data[7]


    def cellClicked(self, row, column):
        
        if column == 2 or column == 4:
            item_key = self.stock_table.item(row, 8).data(QtCore.Qt.DisplayRole)

            QtWidgets.QToolTip.hideText()
            r = self.stock_table.visualItemRect(self.stock_table.item(row, column))
            p = self.stock_table.viewport().mapToGlobal(QtCore.QPoint(r.center().x(), r.top()))

            print(type(self.stock_df.loc[item_key].MIN_DATE))
            if column == 2: QtWidgets.QToolTip.showText(p, self.stock_df.loc[item_key].MIN_DATE.strftime('%Y.%m.%d'))
            if column == 4: QtWidgets.QToolTip.showText(p, self.stock_df.loc[item_key].MAX_DATE.strftime('%Y.%m.%d'))

        elif column == 0:
            item_key = self.stock_table.item(row, 8).data(QtCore.Qt.DisplayRole)            
            item = self.stock_list[item_key]
            webbrowser.open(f"https://www.tradingview.com/chart/?symbol={item['exchange']}%3A{item['symbol']}", new=2)



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    app.aboutToQuit.connect(app.deleteLater)
    window = MoversList()
    window.show()
    app.exec_()



