# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import numpy as np
from uiComps.qtGeneration.AppLauncher_UI import Ui_MainWindow as AppLauncher_UI
import sys
from dataComps.Constants import OrderType, Constants
from uiComps.QHelper import Validator, find_nearest


class AppLauncherWindow(QMainWindow, AppLauncher_UI):

    def __init__(self):
        QMainWindow.__init__(self)
        AppLauncher_UI.__init__(self)

        self.setupUi(self)
        self.toggleAppButtons(False)
        self.setupActions()
        

    def toggleAppButtons(self, enabled):
        for button in self.app_group.buttons():
            button.setEnabled(enabled)


    def setupActions(self):
        self.connect_button.clicked.connect(self.openConnection)
        self.open_options.clicked.connect(self.openOptionsApp)
        self.open_stocks.clicked.connect(self.openStocksApp)
        self.open_downloader.clicked.connect(self.openDownloaderApp)
        self.open_movers.clicked.connect(self.openMoversApp)
        self.open_stepper.clicked.connect(self.openStepperApp)
        self.open_rsi_tracker.clicked.connect(self.openRSIApp)
        self.fetch_rates.clicked.connect(self.downloadShortRateData)
        self.open_symbol.clicked.connect(self.openSymbolLookup)
        self.trading_type_group.buttonClicked.connect(self.radioSelection)
