# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIComps/QTGeneration/OptionsTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(650, 443)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.options_table = QtWidgets.QTableWidget(Form)
        self.options_table.setObjectName("options_table")
        self.options_table.setColumnCount(8)
        self.options_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.options_table.setHorizontalHeaderItem(7, item)
        self.verticalLayout_2.addWidget(self.options_table)
        self.verticalLayout_2.setStretch(0, 8)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.options_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Instrument"))
        item = self.options_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Type"))
        item = self.options_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Expiration"))
        item = self.options_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Strike"))
        item = self.options_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Count"))
        item = self.options_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Price"))
        item = self.options_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Mkt Value"))
        item = self.options_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "UPNL"))
