# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
import numpy as np
from uiComps.qtGeneration.StockPosition_UI import Ui_MainWindow as StockPosition_UI
import sys
from dataComps.Constants import OrderType, Constants
from uiComps.QHelper import Validator, find_nearest


class PositionManagerWindow(QMainWindow, StockPosition_UI):

    def __init__(self):
        QMainWindow.__init__(self)
        StockPosition_UI.__init__(self)

        self.setupUi(self)

        # self.populateBoxes()
        # self.setupGraphs()
        self.setupActions()
        # self.disableInterface() 
        
    def setupActions(self):
        #self.connect_button.clicked.connect(self.openConnection)
        self.position_button.clicked.connect(self.fetchPositions)


