# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optionsGraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QCompleter, QTableWidgetItem
import numpy as np
from dataComps.Constants import Constants, OrderType
from .StairstepWindow import StairstepWindow
import sys, threading
import pandas as pd

from uiComps.Logging import Logger
import webbrowser

from dataComps.UserDataManagement import readStockList
from dataComps.ibFTPdata import getShortDataFor
from dataComps.HistoricalDataManagement import HistoricalDataManager

class StairStepper(StairstepWindow):

    time_period = "Month"

    def __init__(self, history_manager):
        super().__init__()

        self.data_management = history_manager
        self.data_management.data_updater.connect(self.dataUpdate)
        
        file_name, _ = self.stock_lists[0]
        self.stock_list = readStockList(file_name)


    def listSelection(self, value):
        self.bull_table.clearContents()
        self.bull_table.setRowCount(0)
        self.bear_table.clearContents()
        self.bear_table.setRowCount(0)
        
        file_name, _ = self.stock_lists[value]
        self.stock_list = readStockList(file_name)

    def priceUpdate(self):
        self.data_management.fetchPricesFor(self.stock_list)

    def dataUpdate(self, signal):
        print(f"MoversList.dataUpdate: {signal}")

        if signal == Constants.HISTORICAL_DATA_FETCH_COMPLETE:
            histDF = self.data_management.historicalDF
            stock_ids = histDF.UID.unique().tolist()
            bar_types = ['5 mins', '15 mins', '1 hour', '4 hours', '8 hours', '1 day', '1 week']

            high_counts = np.zeros((len(stock_ids), len(bar_types)))
            low_counts = np.zeros((len(stock_ids), len(bar_types)))
        
            high_moves = np.empty((len(stock_ids), len(bar_types)))
            low_moves = np.empty((len(stock_ids), len(bar_types)))
        

            for uid_index, uid in enumerate(stock_ids):
                stock_frame = histDF.loc[histDF.UID == uid]
                for bar_index, bar_type in enumerate(bar_types):
                    lows = stock_frame[stock_frame.BarType == bar_type].Low.tolist()
                    highs = stock_frame[stock_frame.BarType == bar_type].High.tolist()

                    closes = stock_frame[stock_frame.BarType == bar_type].Close.tolist()

                    print(f"For the {bar_type} we find:")
                    # print(stock_frame[stock_frame.BarType == bar_type].Date.tolist())
                    # print(lows)
                    last_low = lows[-1]
                    # print(last_low)
                    last_high = highs[-1]
                    last_price = closes[-1]                    


                    high_maxed = False
                    low_maxed = False
                    low_count = 1
                    high_count = 1

                    low_moves[uid_index, bar_index] = (last_price-last_low)/last_low
                    high_moves[uid_index, bar_index] = (last_price-last_high)/last_high
                    for index in reversed(range(len(lows)-1)):
                        # print(lows[index])
                        if lows[index] > last_low:
                            low_maxed = True
                        else:
                            last_low = lows[index]
                            low_count += 1
                            low_moves[uid_index, bar_index] = 100*(last_price-last_low)/last_low
                        
                        if highs[index] < last_high:
                            high_maxed = True
                        else:
                            last_high = highs[index]
                            high_count += 1
                            high_moves[uid_index, bar_index] = 100*(last_price-last_high)/last_high

                        if low_maxed and high_maxed:
                            break

                    low_counts[uid_index, bar_index] = low_count
                    high_counts[uid_index, bar_index] = high_count

            self.setData(stock_ids, low_counts, low_moves, high_counts, high_moves)
            self.fetch_button.setEnabled(True)

            
            

    def fetchStocks(self):
        self.fetch_button.setEnabled(False)

        self.data_management.getBars(self.stock_list)


    def fetchShortRates(self):
        self.fee_rates = np.ones((len(self.stock_list))) * 500
        self.short_availability = [""] * len(self.stock_list)
        for index, stock in enumerate(self.stock_list):
            short_data = getShortDataFor(stock)
            print(f"For {stock} we found {short_data}")
            if len(short_data) != 0:
                self.fee_rates[index] = float(short_data[6])
                self.short_availability[index] = short_data[7]


    def cellClicked(self, row, column):
        
        if column == 2 or column == 4:
            item_key = self.stock_table.item(row, 8).data(QtCore.Qt.DisplayRole)

            QtWidgets.QToolTip.hideText()
            r = self.stock_table.visualItemRect(self.stock_table.item(row, column))
            p = self.stock_table.viewport().mapToGlobal(QtCore.QPoint(r.center().x(), r.top()))

            print(type(self.stock_df.loc[item_key].MIN_DATE))
            if column == 2: QtWidgets.QToolTip.showText(p, self.stock_df.loc[item_key].MIN_DATE.strftime('%Y.%m.%d'))
            if column == 4: QtWidgets.QToolTip.showText(p, self.stock_df.loc[item_key].MAX_DATE.strftime('%Y.%m.%d'))

        elif column == 0:
            item_key = self.stock_table.item(row, 8).data(QtCore.Qt.DisplayRole)            
            item = self.stock_list[item_key]
            webbrowser.open(f"https://www.tradingview.com/chart/?symbol={item['exchange']}%3A{item['symbol']}", new=2)



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    app.aboutToQuit.connect(app.deleteLater)
    window = MoversList()
    window.show()
    app.exec_()



